name: Run Go Script

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.17'

    - name: Run script
      run: go run main.go -f providers.txt -o resolvers.txt

    - name: Delete old check file
      run: |
        if ls *.date 1> /dev/null 2>&1; then
          rm *.date
        fi

    - name: Create new check file
      run: |
        DATE=$(date '+%Y-%m-%d_%H-%M-%S')
        echo "$DATE" > "${DATE}.date"

    - name: Commit changes
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
      run: |
        git config --local user.email "octocat@github.com"
        git config --local user.name "Octocat"
        git add resolvers.txt *.date
        DATE=$(date '+%Y-%m-%d %H:%M:%S')
        git commit -m "$DATE"
        git push https://$GITHUB_TOKEN@github.com/${{ github.repository }}.git
